# Generated by Django 5.2 on 2025-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='generated_flyer',
            field=models.ImageField(blank=True, null=True, upload_to='generated_flyers/'),
        ),
    ]
